.DEFAULT_GOAL := help
MAKEFLAGS += --no-print-directory
{%- set phony_targets = ["check", "clean", "git", "help", "init", "venv"] %}
{%- if project_name_snake_case == "project_template" %}
{%- set phony_targets = phony_targets + ["test-template"] %}
{%- endif %}
{%- if project_type == "app" %}
{%- set phony_targets = phony_targets + ["run"] %}
{%- endif %}
.PHONY: {{ phony_targets | sort | join(" ") }}
VENV_DIR := .venv
VENV_PYTHON := $(VENV_DIR)/bin/python
VENV_PIP := $(VENV_DIR)/bin/python -m pip

help: ## Show available commands.
	@echo ""
	@echo "Usage: make <target>"
	@echo ""
	@echo "Available targets:"
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | \
		sort | \
		awk 'BEGIN {FS=":.*?## "}; {printf "  %-15s %s\n", $$1, $$2}'
	@echo ""

check: $(VENV_DIR)/bin/{{ pre_commit_tool }} ## Run code quality checks.
	$(VENV_PYTHON) -m {{ pre_commit_tool }} run --all-files

venv: $(VENV_DIR) ## Create the virtual environment and install dependencies.

$(VENV_DIR)/bin/{{ pre_commit_tool }}: $(VENV_DIR)
	@test -f $@ || (rm -rf $(VENV_DIR) && $(MAKE) $(VENV_DIR))

$(VENV_DIR): pyproject.toml
	rm -rf $(VENV_DIR)
	python -m venv $(VENV_DIR)
	$(VENV_PIP) install --upgrade pip setuptools wheel
{%- if project_type == "app" %}
	$(VENV_PIP) install .
	$(VENV_PIP) freeze --exclude {{ project_name_snake_case }} > requirements.txt
	$(VENV_PIP) install .[dev]
{%- else %}
	$(VENV_PIP) install -e .[dev]
{%- endif %}
	$(VENV_PYTHON) -m {{ pre_commit_tool }} install
{%- if with_conventional_commits %}
	$(VENV_PYTHON) -m {{ pre_commit_tool }} install --hook-type commit-msg commitizen
{%- endif %}
	$(VENV_PYTHON) -m {{ pre_commit_tool }} autoupdate
{%- if typing %}
	$(VENV_PYTHON) -m mypy --install-types --non-interactive
{%- endif %}

clean: ## Remove untracked files (keeps the .venv folder and .env files).
	@FILES="$$(git clean -xdn \
		-e $(VENV_DIR)/ \
		-e '*.py' \
		-e .env )"; \
	if [ -z "$$FILES" ]; then \
		echo "Nothing to clean."; \
	else \
		printf "%s\n" "$$FILES"; \
		read -p "Delete these files? [y/N] " ANSWER; \
		if [ "$$ANSWER" = "y" ] || [ "$$ANSWER" = "Y" ]; then \
			git clean -xd -f \
				-e $(VENV_DIR)/ \
				-e '*.py' \
				-e .env ; \
		fi \
	fi

git:
	@if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then \
		echo "Git repository already exists."; \
	else \
		echo "Initializing git repository (master branch)..."; \
		git init -b master; \
	fi

init: git clean venv check ## Clean, install dependencies, and run checks.

{%- if project_name_snake_case == "project_template" %}

test-template: $(VENV_DIR) ## Test the Copier template by applying it to itself.
	$(VENV_PYTHON) scripts/update_precommit_template.py || true
	$(VENV_PYTHON) -m copier copy --defaults --overwrite --vcs-ref=HEAD . .
{%- endif %}
{%- if project_type == "app" %}

run: $(VENV_DIR) ## Run the {{ project_name }} app
	$(VENV_PYTHON) main.py
{%- endif %}
