.DEFAULT_GOAL := help

VENV_DIR := .venv
VENV_PYTHON := $(VENV_DIR)/bin/python
VENV_PIP := $(VENV_DIR)/bin/python -m pip

.PHONY: help init venv check clean {% if project_slug == "project_template" %} test-template{% endif %}

help:  ## Show this help message.
	grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | \
	awk 'BEGIN {FS = ":.*?## "}; {printf "  %-15s %s\n", $$1, $$2}'

check: $(VENV_DIR){% if project_slug == "project_template" %}/bin/{{ pre_commit_tool }}{% endif %}  ## Run {{ pre_commit_tool }} checks.
	$(VENV_PYTHON) -m {{ pre_commit_tool }} run --all-files

venv: $(VENV_DIR)  # Create virtual environment and install dependencies.{% if project_slug == "project_template" %}
$(VENV_DIR)/bin/{{ pre_commit_tool }}: venv{% endif %}

$(VENV_DIR): pyproject.toml
	rm -rf $(VENV_DIR)
	python -m venv $(VENV_DIR)
	$(VENV_PIP) install --upgrade pip setuptools wheel
	{% if package_or_app == "package" %}$(VENV_PIP) install -e .
	$(VENV_PIP) freeze --exclude-editable > requirements.txt
	$(VENV_PIP) install -e .[dev]{% else %}$(VENV_PIP) install .
	$(VENV_PIP) freeze --exclude {{ project_slug }} > requirements.txt
	$(VENV_PIP) install .[dev]{% endif %}
	$(VENV_PYTHON) -m {{ pre_commit_tool }} install
	$(VENV_PYTHON) -m {{ pre_commit_tool }} autoupdate


clean:  ## Clean untracked files (except virtual environment and Python files).
	@FILES="$$(git clean -xdn -e $(VENV_DIR)/ -e '*.py')"; \
	if [ -z "$$FILES" ]; then \
		echo "Nothing to clean."; \
	else \
		printf "%s\n" "$$FILES"; \
		read -p "Delete these files? [y/N] " ANSWER; \
		if [ "$$ANSWER" = "y" ] || [ "$$ANSWER" = "Y" ]; then \
			git clean -xd -f -e $(VENV_DIR)/ -e '*.py'; \
		fi \
	fi

init: clean venv check ## Clean untracked files (except virtual environment and Python files).

{% if project_slug == "project_template" %}
$(VENV_DIR)/bin/copier:
	rm -rf $(VENV_DIR)
	python -m venv $(VENV_DIR)
	$(VENV_PIP) install --upgrade pip setuptools wheel
	$(VENV_PIP) install copier

test-template: $(VENV_DIR)/bin/copier  ## Test the copier template by applying it to itself
	$(VENV_PYTHON) -m copier copy --defaults --overwrite . .{% endif %}
