.DEFAULT_GOAL := help

VENV_DIR := .venv
VENV_PYTHON := $(VENV_DIR)/bin/python
VENV_PIP := $(VENV_DIR)/bin/python -m pip

.PHONY: help init venv check clean {% if project_slug == "project_template" %}test-template{% endif %}

help: ## Show available commands.
	@echo ""
	@echo "Usage: make <target>"
	@echo ""
	@echo "Available targets:"
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | \
		sort | \
		awk 'BEGIN {FS=":.*?## "}; {printf "  %-15s %s\n", $$1, $$2}'
	@echo ""

check: $(VENV_DIR)/bin/{{ pre_commit_tool }} ## Run code quality checks.
	$(VENV_PYTHON) -m {{ pre_commit_tool }} run --all-files

venv: $(VENV_DIR) ## Create the virtual environment and install dependencies.

$(VENV_DIR)/bin/{{ pre_commit_tool }}: venv

$(VENV_DIR): pyproject.toml
	rm -rf $(VENV_DIR)
	python -m venv $(VENV_DIR)
	$(VENV_PIP) install --upgrade pip setuptools wheel
	{% if package_or_app == "app" %}$(VENV_PIP) install .
	$(VENV_PIP) freeze --exclude {{ project_slug }} > requirements.txt
	$(VENV_PIP) install .[dev]{% else %}$(VENV_PIP) install -e .[dev]{% endif %}
	$(VENV_PYTHON) -m {{ pre_commit_tool }} install
	$(VENV_PYTHON) -m {{ pre_commit_tool }} autoupdate

clean: ## Remove untracked files (keeps the venv).
	@FILES="$$(git clean -xdn -e $(VENV_DIR)/ -e '*.py')"; \
	if [ -z "$$FILES" ]; then \
		echo "Nothing to clean."; \
	else \
		printf "%s\n" "$$FILES"; \
		read -p "Delete these files? [y/N] " ANSWER; \
		if [ "$$ANSWER" = "y" ] || [ "$$ANSWER" = "Y" ]; then \
			git clean -xd -f -e $(VENV_DIR)/ -e '*.py'; \
		fi \
	fi

init: clean venv check ## Clean, install dependencies, and run checks.{% if project_slug == "project_template" %}

$(VENV_DIR)/bin/copier:
	rm -rf $(VENV_DIR)
	python -m venv $(VENV_DIR)
	$(VENV_PIP) install --upgrade pip setuptools wheel
	$(VENV_PIP) install copier

test-template: $(VENV_DIR)/bin/copier ## Test the Copier template by applying it to itself.
	$(VENV_PYTHON) -m copier copy --defaults --overwrite . .{% endif %}
